### ISSUE TITLE
py27 unicode 兼容性问题

### ISSUE THREAD

**Issue by rexzhang** [qiniu/python-sdk#185]
```
#!/usr/bin/env python
#coding=utf-8

from __future__ import print_function, unicode_literals, absolute_import
from qiniu import Auth

class settings():
    QINIU_ACCESS_KEY = 'aaaaa'
    QINIU_SECRET_KEY = 'sssss'
    QINIU_BUCKET_NAME = 'bbbbb'
    QINIU_TOKEN_EXPRIE_TIME = 3600

key = ''

q = Auth(settings.QINIU_ACCESS_KEY, settings.QINIU_SECRET_KEY)
token = q.upload_token(settings.QINIU_BUCKET_NAME, key, settings.QINIU_TOKEN_EXPRIE_TIME)
```

错误提示为

```
Traceback (most recent call last):
  File "/Users/rex/py/test.py", line 18, in <module>
    token = q.upload_token(settings.QINIU_BUCKET_NAME, key, settings.QINIU_TOKEN_EXPRIE_TIME)
  File "/usr/local/lib/python2.7/site-packages/qiniu/auth.py", line 151, in upload_token
    return self.__upload_token(args)
  File "/usr/local/lib/python2.7/site-packages/qiniu/auth.py", line 155, in __upload_token
    return self.token_with_data(data)
  File "/usr/local/lib/python2.7/site-packages/qiniu/auth.py", line 69, in token_with_data
    return '{0}:{1}:{2}'.format(self.__access_key, self.__token(data), data)
  File "/usr/local/lib/python2.7/site-packages/qiniu/auth.py", line 61, in __token
    hashed = hmac.new(self.__secret_key, data, sha1)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
```

如果注释掉 第4行 即可正常工作

**Comment by hunter007** [comment]
我也在 django 里遇到了这个问题。为了方便，我在 settings.py 中使用了`from __future__ import unicode_literals`。的确想你说的那样，删除这一行可以工作。但最根本的原因在：
compat.py 中的 b()和 s()没有起到作用。在 python2.x 中，建议改为

```
def b(data):
    return bytes(data)

def s(data):
    return bytes(data)
```

**Comment by longbai** [comment]
@hunter007 多谢，我看下
