### ISSUE TITLE
上传视频文件时出现 异常

### ISSUE THREAD

**Issue by wbo4958** [qiniu/python-sdk#223]
急急急急

上传中文名字的视频就会出现这样的问题， 如果改成英文就能上传

这个是不支持中文的么？
            token = q.upload_token(bucket_name, None, 3600)
            print 'putting %s to qiniu' % localfile
            ret, info = put_file(token, None, localfile)
            print '    Got info ....', info
            print '        ret,' ,ret
            return ret['key']

Traceback (most recent call last):
  File "upload.py", line 110, in uploading_to_qiniu
    ret, info = put_file(token, None, localfile)
  File "/usr/local/lib/python2.7/dist-packages/qiniu/services/storage/uploader.py", line 61, in put_file
    modify_time=(int)(os.path.getmtime(file_path)))
  File "/usr/local/lib/python2.7/dist-packages/qiniu/services/storage/uploader.py", line 107, in put_stream
    return task.upload()
  File "/usr/local/lib/python2.7/dist-packages/qiniu/services/storage/uploader.py", line 189, in upload
    self.record_upload_progress(offset)
  File "/usr/local/lib/python2.7/dist-packages/qiniu/services/storage/uploader.py", line 154, in record_upload_progress
    self.upload_progress_recorder.set_upload_record(self.file_name, self.key, record_data)
  File "/usr/local/lib/python2.7/dist-packages/qiniu/services/storage/upload_progress_recorder.py", line 45, in set_upload_record
    with open(upload_record_file_path, 'w') as f:
IOError: [Errno 2] No such file or directory: u'/tmp/Tm9uZS/mgIDljJbluILpuaTln47ljLrlnajpmaLprYXlipvoiJ7nkLzlgaXouqvpmJ/jgIrkuIfmoJHnuYHoirHjgIvjgIrkuK3lm73lhrLlhrLlhrLjgItfMTQ3NjAxMjMwOC42My5tcDQ='

**Comment by wbo4958** [comment]
具体 在
set_upload_record

base64.b64encode(key.encode('utf-8')).decode('utf-8')
如果是中文的

code出来 有下划线， 这样就会找不到

u'Tm9uZS/mgIDljJYubXA0'

**Comment by JianxunRao** [comment]
这么明显的问题,直到现在最新的SDK都没有解决= =

**Comment by jemygraw** [comment]
FIXED IN https://github.com/qiniu/python-sdk/commit/0fe927721d9a99cbec69e46ec2eb058a46c13155

使用md5来计算断点续传的进度文件名
