### ISSUE TITLE
执行测试脚本提示SSL认证失败

### ISSUE THREAD

**Issue by onewesong** [qiniu/python-sdk#242]
Traceback (most recent call last):
  File "test11.py", line 26, in <module>
    ret, info = put_file(token, key, localfile)
  File "/usr/lib/python2.7/site-packages/qiniu/services/storage/uploader.py", line 64, in put_file
    ret, info = _form_put(up_token, key, input_stream, params, mime_type, crc, progress_handler, file_name)
  File "/usr/lib/python2.7/site-packages/qiniu/services/storage/uploader.py", line 80, in _form_put
    url = config.get_default('default_zone').get_up_host_by_token(up_token) + '/'
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 31, in get_up_host_by_token
    up_hosts = self.get_up_host(ak, bucket)
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 50, in get_up_host
    bucket_hosts = self.get_bucket_hosts(ak, bucket)
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 76, in get_bucket_hosts
    hosts = compat.json.loads(self.bucket_hosts(ak, bucket))
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 128, in bucket_hosts
    ret = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)

**Comment by lilanjun2016** [comment]
您可以看下examples文件夹下的py示例demo的。另外您这个是想做什么操作的啊

**Comment by kongminhao** [comment]
同出现上述问题，在本机上不会出现问题，OSX 10.11.2

但在服务器上就有这个问题

File "/usr/lib/python2.7/site-packages/qiniu/services/storage/uploader.py", line 64, in put_file
    ret, info = _form_put(up_token, key, input_stream, params, mime_type, crc, progress_handler, file_name)
  File "/usr/lib/python2.7/site-packages/qiniu/services/storage/uploader.py", line 80, in _form_put
    url = config.get_default('default_zone').get_up_host_by_token(up_token) + '/'
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 31, in get_up_host_by_token
    up_hosts = self.get_up_host(ak, bucket)
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 50, in get_up_host
    bucket_hosts = self.get_bucket_hosts(ak, bucket)
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 76, in get_bucket_hosts
    hosts = compat.json.loads(self.bucket_hosts(ak, bucket))
  File "/usr/lib/python2.7/site-packages/qiniu/zone.py", line 128, in bucket_hosts
    ret = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

执行的就是一个普通的打包上传工作。

**Comment by kongminhao** [comment]
阿里云，但是我在阿里云上搭建了一个ss做测试，发现应该不是qiniu禁用了阿里的ip。

**Comment by SeanChense** [comment]
我也遇到了这个问题，就把文档中的上传脚本运行了下。

**Comment by SeanChense** [comment]
```
sudo pip uninstall -y certifi
sudo pip install certifi==2017.1.23
```

虽然不是很懂，看样子是更新证书可以搞定

**Comment by SimonLv2015** [comment]
更新证书无效，看起来像是七牛云服务器升级了，之前跑的好好的，突然就不行了

**Comment by jemygraw** [comment]
```
Python 2.7.12 (default, Jul 29 2016, 15:26:22) fixed the mentioned issue. This information might help someone else.
```
麻烦python升级到 2.7.12或以上版本。

**Comment by zhaoqz** [comment]
可以参考这个看看：
https://github.com/doraemonext/wechat-python-sdk/issues/66
最后有解决方案，我遇到同样错误，这么处理就好了。
在这之前，还把系统的python 2.7.5升级到最新版的2.7.13,pyopenssl等都升级了。没有解决。用下面的方法就好了，推测原理是把服务器的证书导入到python相关的配置文件了。

> 我在本机没有遇到这个问题，但是在centos7 的 docker 中遇到相同的问题，我用这个命令解决了它
cat /etc/ssl/certs/ca-bundle.crt >>$(python -c 'import requests; print requests.certs.where()')
