### ISSUE TITLE
ImportError: No module named 'qiniu.services.pili'

### ISSUE THREAD

**Issue by fiveddd** [qiniu/python-sdk#307]
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from application import create_app_for_cli
...
    from runtimes.qiniu import get_private_url_by_filename, get_public_url_by_filename
  File "/home/gitlab-runner/builds/54616be3/0/xxx/qiniu.py", line 4, in <module>
    from qiniu import Auth, BucketManager
  File "/home/gitlab-runner/builds/54616be3/0/xxx/venv/lib/python3.5/site-packages/qiniu/__init__.py", line 28, in <module>
    from .services.pili.rtc_server_manager import RtcServer, get_room_token

----

ci由7.2.0自动升级到7.2.1报bug

**Comment by jemygraw** [comment]
这个是库发布有问题，我们fix下。稍等再试试。

**Comment by jemygraw** [comment]
7.2.2发布了。
