### ISSUE TITLE
7.14.0 升级后会报错

### ISSUE THREAD

**Issue by benimang** [qiniu/python-sdk#451]
[WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\Xxxxx\\AppData\\Local\\Temp\\qn-regions-cache.jsonl.shrink' -> 'C:\\Users\\Xxxxx\\AppData\\Local\\Temp\\qn-regions-cache.jsonl'

触发报错的接口是 bucketManager.stat
这个是报错信息，第一次运行的时候不会拨错可以正常，第二次后就会报错
我的电脑环境是 Windows 11 ，我试过公司的电脑和自己家里的电脑，都会出现这样的问题
我回退到之前的版本 7.13.2 是一切正常，我相信应该是由于版本升级所带来的问题

希望早日定位问题并修复，谢谢

**Comment by YahuiWong** [comment]
windows下遇到了相同的错误了，希望可以改过来

**Comment by cogitozz** [comment]
遇到同样的错误，第一次虽然上传成功了，但是会报failed to cache regions result to file错误，堆栈显示：
Traceback (most recent call last):
  File "C:\ProfessionalTechnologyStudy\ProgrammingLanguage\python_introduction_lucubrate\venv\lib\site-packages\qiniu\http\regions_provider.py", line 448, in set_regions
    'regions': [_persist_region(r) for r in regions]
  File "C:\ProfessionalTechnologyStudy\ProgrammingLanguage\python_introduction_lucubrate\venv\lib\site-packages\qiniu\http\regions_provider.py", line 448, in <listcomp>
    'regions': [_persist_region(r) for r in regions]
  File "C:\ProfessionalTechnologyStudy\ProgrammingLanguage\python_introduction_lucubrate\venv\lib\site-packages\qiniu\http\regions_provider.py", line 267, in _persist_region
    createTime=int(float(region.create_time.strftime('%s.%f')) * 1000)
ValueError: Invalid format string
createtime这里报错。

然后第二次再运行就报文件已存在错误。删掉临时文件后再次运行又回到第一个错误。

**Comment by cogitozz** [comment]
把%s改成%S就没问题了，不知道原本是不是打算要这样取的。

**Comment by lihsai0** [comment]
@benimang @YahuiWong @cogitozz 

Windows 的各个兼容问题已定位到问题。
目前 GitHub Actions 的测试新增了 Windows 的环境，整个测试流程还有点问题，正在调试中。
